export const bugBountyCourses = [
  {
    id: "xss",
    title: "Cross-Site Scripting (XSS)",
    description: "Complete guide to finding and exploiting XSS vulnerabilities in modern web applications.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/JLWspp1BwpVFXPBeITBr/image.png",
    level: "Beginner to Advanced",
    category: "Web",
  },
  {
    id: "sqli",
    title: "SQL Injection",
    description: "From basic to advanced SQL Injection techniques, bypasses and real-world exploitation.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/erUlFWe72AQA16NPyk67/image.png",
    level: "Intermediate",
    category: "Web",
  },
  {
    id: "xxe",
    title: "XML External Entity (XXE)",
    description: "Deep dive into XXE attacks, out-of-band techniques and modern bypasses.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/3JD3CxPEffWdlS4ozIF3/image.png",
    level: "Intermediate",
    category: "Web",
  },
  {
    id: "ssrf",
    title: "Server-Side Request Forgery (SSRF)",
    description: "SSRF exploitation, cloud metadata attacks and advanced bypass methods.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/AyOdumL16sagmKDR6yDT/image.png",
    level: "Advanced",
    category: "Web",
  },
  {
    id: "idor",
    title: "Insecure Direct Object Reference (IDOR)",
    description: "Finding and exploiting IDOR vulnerabilities in APIs and web applications.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/xcXx2yoiDKhOUdPvmijF/image.png",
    level: "Beginner",
    category: "Web",
  },
  {
    id: "auth-bypass",
    title: "Authentication Bypass",
    description: "Common authentication flaws, JWT attacks and session management issues.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/f7XsxRyan8LAb2CNqv7Z/image.png",
    level: "Intermediate",
    category: "Web",
  },
  {
    id: "rce",
    title: "Remote Code Execution (RCE)",
    description: "From command injection to full RCE chains in real bug bounty targets.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/CzGI9ssKrxmNtimPFLzG/image.png",
    level: "Advanced",
    category: "Web",
  },
  {
    id: "api-security",
    title: "API Security Testing",
    description: "REST & GraphQL API vulnerabilities, mass assignment, BOLA and more.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/hPSeChyOesXZ7lQ5bXYs/image.png",
    level: "Intermediate",
    category: "API",
  },
  {
    id: "business-logic",
    title: "Business Logic Flaws",
    description: "Finding logic bugs that scanners miss – race conditions, price manipulation etc.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/OoPSZSDlvGyeb2ixCrkS/image.png",
    level: "Advanced",
    category: "Web",
  },
  {
    id: "file-upload",
    title: "File Upload Vulnerabilities",
    description: "Bypassing file upload restrictions and achieving RCE through uploads.",
    image: "https://plain-apac-prod-public.komododecks.com/202610/03/ORFAi1XPZwYA1yEp7zza/image.png",
    level: "Intermediate",
    category: "Web",
  },
];